var hierarchy =
[
    [ "vafmbase.Circuit", "classvafmbase_1_1_circuit.html", [
      [ "vafmcircuits.Machine", "classvafmcircuits_1_1_machine.html", null ],
      [ "vafmcircuits_avg.avg", "classvafmcircuits__avg_1_1avg.html", null ],
      [ "vafmcircuits_Cantilever.AdvancedCantilever", "classvafmcircuits___cantilever_1_1_advanced_cantilever.html", null ],
      [ "vafmcircuits_Cantilever.Cantilever", "classvafmcircuits___cantilever_1_1_cantilever.html", null ],
      [ "vafmcircuits_Comparison.Equal", "classvafmcircuits___comparison_1_1_equal.html", null ],
      [ "vafmcircuits_Comparison.GreaterOrEqual", "classvafmcircuits___comparison_1_1_greater_or_equal.html", null ],
      [ "vafmcircuits_Comparison.LessOrEqual", "classvafmcircuits___comparison_1_1_less_or_equal.html", null ],
      [ "vafmcircuits_control.PI", "classvafmcircuits__control_1_1_p_i.html", null ],
      [ "vafmcircuits_control.PID", "classvafmcircuits__control_1_1_p_i_d.html", null ],
      [ "vafmcircuits_Filters.RCHP", "classvafmcircuits___filters_1_1_r_c_h_p.html", null ],
      [ "vafmcircuits_Filters.RCLP", "classvafmcircuits___filters_1_1_r_c_l_p.html", null ],
      [ "vafmcircuits_Filters.SKBP", "classvafmcircuits___filters_1_1_s_k_b_p.html", null ],
      [ "vafmcircuits_Filters.SKHP", "classvafmcircuits___filters_1_1_s_k_h_p.html", null ],
      [ "vafmcircuits_Filters.SKLP", "classvafmcircuits___filters_1_1_s_k_l_p.html", null ],
      [ "vafmcircuits_FlipFlop.DFlipFlop", "classvafmcircuits___flip_flop_1_1_d_flip_flop.html", null ],
      [ "vafmcircuits_FlipFlop.DRFlipFlop", "classvafmcircuits___flip_flop_1_1_d_r_flip_flop.html", null ],
      [ "vafmcircuits_FlipFlop.JKFlipFlop", "classvafmcircuits___flip_flop_1_1_j_k_flip_flop.html", null ],
      [ "vafmcircuits_FlipFlop.SRFlipFlop", "classvafmcircuits___flip_flop_1_1_s_r_flip_flop.html", null ],
      [ "vafmcircuits_Interpolation.i1Dlin", "classvafmcircuits___interpolation_1_1i1_dlin.html", null ],
      [ "vafmcircuits_Interpolation.i3Dlin", "classvafmcircuits___interpolation_1_1i3_dlin.html", null ],
      [ "vafmcircuits_Logic.AND", "classvafmcircuits___logic_1_1_a_n_d.html", null ],
      [ "vafmcircuits_Logic.NOR", "classvafmcircuits___logic_1_1_n_o_r.html", null ],
      [ "vafmcircuits_Logic.NOT", "classvafmcircuits___logic_1_1_n_o_t.html", null ],
      [ "vafmcircuits_Logic.OR", "classvafmcircuits___logic_1_1_o_r.html", null ],
      [ "vafmcircuits_Logic.XOR", "classvafmcircuits___logic_1_1_x_o_r.html", null ],
      [ "vafmcircuits_math.opAbs", "classvafmcircuits__math_1_1op_abs.html", null ],
      [ "vafmcircuits_math.opAdd", "classvafmcircuits__math_1_1op_add.html", null ],
      [ "vafmcircuits_math.opCos", "classvafmcircuits__math_1_1op_cos.html", null ],
      [ "vafmcircuits_math.opDiv", "classvafmcircuits__math_1_1op_div.html", null ],
      [ "vafmcircuits_math.opLinC", "classvafmcircuits__math_1_1op_lin_c.html", null ],
      [ "vafmcircuits_math.opMul", "classvafmcircuits__math_1_1op_mul.html", null ],
      [ "vafmcircuits_math.opPow", "classvafmcircuits__math_1_1op_pow.html", null ],
      [ "vafmcircuits_math.opSin", "classvafmcircuits__math_1_1op_sin.html", null ],
      [ "vafmcircuits_math.opSub", "classvafmcircuits__math_1_1op_sub.html", null ],
      [ "vafmcircuits_math.Perlin", "classvafmcircuits__math_1_1_perlin.html", null ],
      [ "vafmcircuits_output.output", "classvafmcircuits__output_1_1output.html", null ],
      [ "vafmcircuits_Scanner.Scanner", "classvafmcircuits___scanner_1_1_scanner.html", null ],
      [ "vafmcircuits_signal_gens.square", "classvafmcircuits__signal__gens_1_1square.html", null ],
      [ "vafmcircuits_signal_gens.waver", "classvafmcircuits__signal__gens_1_1waver.html", null ],
      [ "vafmcircuits_signal_processing.delay", "classvafmcircuits__signal__processing_1_1delay.html", null ],
      [ "vafmcircuits_signal_processing.derivative", "classvafmcircuits__signal__processing_1_1derivative.html", null ],
      [ "vafmcircuits_signal_processing.flip", "classvafmcircuits__signal__processing_1_1flip.html", null ],
      [ "vafmcircuits_signal_processing.gain", "classvafmcircuits__signal__processing_1_1gain.html", null ],
      [ "vafmcircuits_signal_processing.integral", "classvafmcircuits__signal__processing_1_1integral.html", null ],
      [ "vafmcircuits_signal_processing.limiter", "classvafmcircuits__signal__processing_1_1limiter.html", null ],
      [ "vafmcircuits_signal_processing.minmax", "classvafmcircuits__signal__processing_1_1minmax.html", null ],
      [ "vafmcircuits_signal_processing.peaker", "classvafmcircuits__signal__processing_1_1peaker.html", null ],
      [ "vafmcircuits_signal_processing.phasor", "classvafmcircuits__signal__processing_1_1phasor.html", null ],
      [ "vafmcircuits_VDW.VDW", "classvafmcircuits___v_d_w_1_1_v_d_w.html", null ]
    ] ],
    [ "vafmbase.Feed", "classvafmbase_1_1_feed.html", null ]
];